package edu.cw.cbr.model.domain;

// Generated 27.04.2013 1:42:58 by Hibernate Tools 4.0.0

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Developer generated by hbm2java
 */
@Entity
@Table(name = "developer", schema = "public")
public class Developer extends ArrayAble{

	private int developerId;
	private String developerName;

	public Developer(){
	}

	public Developer(String developerName)
			throws IllegalArgumentException{
		if (developerName.isEmpty())
			throw new IllegalArgumentException();
		this.developerName = developerName;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "developer_id", unique = true, nullable = false)
	public int getDeveloperId() {
		return this.developerId;
	}

	public void setDeveloperId(int developerId) {
		this.developerId = developerId;
	}

	@Column(name = "developer_name", nullable = false, length = 256)
	public String getDeveloperName() {
		return this.developerName;
	}

	public void setDeveloperName(String developerName) {
		this.developerName = developerName;
	}

	@Override
	public List<Object> toList() {
		List<Object> instDataList = new ArrayList<Object>();
		instDataList.add(this.getDeveloperId());
		instDataList.add(this.getDeveloperName());
		return instDataList;
	}

}
