package edu.cw.cbr.model.domain;

// Generated 27.04.2013 1:42:58 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * DeviceState generated by hbm2java
 */
@Entity
@Table(name = "devicestate", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = {
		"state_id", "device_id" }))
public class DeviceState{

	private int deviceStateId;
	private State state;
	private Device device;

	public DeviceState() {
	}

	public DeviceState(int deviceStateId, State state, Device device) {
		this.deviceStateId = deviceStateId;
		this.state = state;
		this.device = device;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "device_state_id", unique = true, nullable = false)
	public int getDeviceStateId() {
		return this.deviceStateId;
	}

	public void setDeviceStateId(int deviceStateId) {
		this.deviceStateId = deviceStateId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "state_id", nullable = false)
	public State getState() {
		return this.state;
	}

	public void setState(State state) {
		this.state = state;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "device_id", nullable = false)
	public Device getDevice() {
		return this.device;
	}

	public void setDevice(Device device) {
		this.device = device;
	}

}
