package edu.cw.cbr.model.domain;

// Generated 27.04.2013 1:42:58 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Device generated by hbm2java
 */
@Entity
@Table(name = "device", schema = "public")
public class Device{

	private int deviceId;
	private Developer developer;
	private String deviceName;

	public Device() {
	}

	public Device(int deviceId, Developer developer, String deviceName) {
		this.deviceId = deviceId;
		this.developer = developer;
		this.deviceName = deviceName;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "device_id", unique = true, nullable = false)
	public int getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(int deviceId) {
		this.deviceId = deviceId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "developer_id", nullable = false)
	public Developer getDeveloper() {
		return this.developer;
	}

	public void setDeveloper(Developer developer) {
		this.developer = developer;
	}

	@Column(name = "device_name", nullable = false, length = 256)
	public String getDeviceName() {
		return this.deviceName;
	}

	public void setDeviceName(String deviceName) {
		this.deviceName = deviceName;
	}

}
