package edu.cw.cbr.model.domain;

// Generated 27.04.2013 1:42:58 by Hibernate Tools 4.0.0

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import edu.cw.cbr.model.DeveloperUtil;

/**
 * Device generated by hbm2java
 */
@Entity
@Inheritance(strategy = InheritanceType.TABLE_PER_CLASS)
@Table(name = "device", schema = "public")
public class Device extends ArrayAble{

	private int deviceId;
	private Developer developer;
	private String deviceName;

	public Device() {
	}

	public Device(int developerId, String deviceName) {
		if (deviceName.isEmpty())
			throw new IllegalArgumentException();
		this.deviceName = deviceName;
		try {
			DeveloperUtil devUtil = new DeveloperUtil();
			this.developer = devUtil.getEntity(developerId);
			if (developer == null)
				throw new IllegalArgumentException();
		} catch (SQLException e) {
			e.printStackTrace();
			throw new IllegalArgumentException();
		}
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "device_id", updatable = false, unique = true, nullable = false)
	public int getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(int deviceId) {
		this.deviceId = deviceId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "developer_id", nullable = false)
	public Developer getDeveloper() {
		return this.developer;
	}

	public void setDeveloper(Developer developer) {
		this.developer = developer;
	}

	@Column(name = "device_name", nullable = false, length = 256)
	public String getDeviceName() {
		return this.deviceName;
	}

	public void setDeviceName(String deviceName) {
		this.deviceName = deviceName;
	}

	@Override
	public List<Object> toList() {
		List<Object> lData = new ArrayList<Object>();
		lData.add(this.getDeviceId());
		lData.add(this.getDeveloper().getDeveloperName());
		lData.add(this.getDeviceName());
		return lData;
	}

}
