package edu.cw.cbr.model.domain;

// Generated 27.04.2013 1:42:58 by Hibernate Tools 4.0.0

import java.sql.SQLException;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import edu.cw.cbr.model.HardwareComponentUtil;

/**
 * DeviceHardwareComponent generated by hbm2java
 */
@Entity
@Table(name = "devicehardwarecomponent", schema = "public")
public class DeviceHardwareComponent extends ArrayAble{

	private int componentId;
	private Device device;
	private HardwareComponent hardwareComponent;

	public DeviceHardwareComponent() {
	}

	public <T extends HardwareComponent>DeviceHardwareComponent(Device device,
			int hardwareComponentId, Class<T> cl, int type) {
		if (device == null)
			throw new IllegalArgumentException();
		this.device = device;
		try {
			hardwareComponent = new HardwareComponentUtil<T>(cl, type)
					.getEntity(hardwareComponentId);
			if(hardwareComponent == null)
				throw new IllegalArgumentException();
		} catch (SQLException e) {
			throw new IllegalArgumentException();
		}
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "component_id", unique = true, nullable = false)
	public int getComponentId() {
		return this.componentId;
	}

	public void setComponentId(int componentId) {
		this.componentId = componentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "device_id", nullable = false)
	public Device getDevice() {
		return this.device;
	}

	public void setDevice(Device device) {
		this.device = device;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "hardware_component_id", nullable = false)
	public HardwareComponent getHardwareComponent() {
		return this.hardwareComponent;
	}

	public void setHardwareComponent(HardwareComponent hardwareComponent) {
		this.hardwareComponent = hardwareComponent;
	}

	@Override
	public List<Object> toList() {
		// TODO Auto-generated method stub
		return null;
	}

}
