package edu.cw.cbr.model.domain;

// Generated 27.04.2013 1:42:58 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * HardwareComponentType generated by hbm2java
 */
@Entity
@Table(name = "hardwarecomponenttype", schema = "public")
public class HardwareComponentType{

	private int hardwareComponentTypeId;
	private String hardwareComponentTypeName;

	public HardwareComponentType() {
	}

	public HardwareComponentType(int hardwareComponentTypeId,
			String hardwareComponentTypeName) {
		this.hardwareComponentTypeId = hardwareComponentTypeId;
		this.hardwareComponentTypeName = hardwareComponentTypeName;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "hardware_component_type_id", unique = true, nullable = false)
	public int getHardwareComponentTypeId() {
		return this.hardwareComponentTypeId;
	}

	public void setHardwareComponentTypeId(int hardwareComponentTypeId) {
		this.hardwareComponentTypeId = hardwareComponentTypeId;
	}

	@Column(name = "hardware_component_type_name", nullable = false, length = 256)
	public String getHardwareComponentTypeName() {
		return this.hardwareComponentTypeName;
	}

	public void setHardwareComponentTypeName(String hardwareComponentTypeName) {
		this.hardwareComponentTypeName = hardwareComponentTypeName;
	}

}
