package edu.cw.cbr.model.domain;

// Generated 27.04.2013 1:42:58 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Precedent generated by hbm2java
 */
@Entity
@Table(name = "precedent", schema = "public")
public class Precedent{

	private int precedentId;
	private Task task;
	private DeviceState deviceState;
	private float timeToSolve;
	private Boolean isSolvedCorrectly;
	public Precedent() {
	}

	public Precedent(int precedentId, Task task, DeviceState deviceState,
			float timeToSolve) {
		this.precedentId = precedentId;
		this.task = task;
		this.deviceState = deviceState;
		this.timeToSolve = timeToSolve;
	}

	public Precedent(int precedentId, Task task, DeviceState deviceState,
			float timeToSolve, Boolean isSolvedCorrectly) {
		this.precedentId = precedentId;
		this.task = task;
		this.deviceState = deviceState;
		this.timeToSolve = timeToSolve;
		this.isSolvedCorrectly = isSolvedCorrectly;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "precedent_id", unique = true, nullable = false)
	public int getPrecedentId() {
		return this.precedentId;
	}

	public void setPrecedentId(int precedentId) {
		this.precedentId = precedentId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "task_id", nullable = false)
	public Task getTask() {
		return this.task;
	}

	public void setTask(Task task) {
		this.task = task;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "device_state_id", nullable = false)
	public DeviceState getDevicestate() {
		return this.deviceState;
	}

	public void setDevicestate(DeviceState deviceState) {
		this.deviceState = deviceState;
	}

	@Column(name = "time_to_solve", nullable = false, precision = 8, scale = 8)
	public float getTimeToSolve() {
		return this.timeToSolve;
	}

	public void setTimeToSolve(float timeToSolve) {
		this.timeToSolve = timeToSolve;
	}

	@Column(name = "is_solved_correctly")
	public Boolean isSolvedCorrectly() {
		return this.isSolvedCorrectly;
	}

	public void setSolvedCorrectly(Boolean isSolvedCorrectly) {
		this.isSolvedCorrectly = isSolvedCorrectly;
	}

}
