package edu.cw.cbr.model.domain;

// Generated 27.04.2013 1:42:58 by Hibernate Tools 4.0.0

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usertype generated by hbm2java
 */
@Entity
@Table(name = "usertype", schema = "public")
public class Usertype implements Serializable{

	private static final long serialVersionUID = 7810637874992156548L;
	private int userTypeId;
	private String userTypeName;
	//private Set<Sysuser> sysusers = new HashSet<Sysuser>(0);

	public Usertype() {
	}

	public Usertype(int userTypeId, String userTypeName) {
		this.userTypeId = userTypeId;
		this.userTypeName = userTypeName;
	}

	@Id
	@Column(name = "user_type_id", unique = true, nullable = false)
	public int getUserTypeId() {
		return this.userTypeId;
	}

	public void setUserTypeId(int userTypeId) {
		this.userTypeId = userTypeId;
	}

	@Column(name = "user_type_name", nullable = false, length = 256)
	public String getUserTypeName() {
		return this.userTypeName;
	}

	public void setUserTypeName(String userTypeName) {
		this.userTypeName = userTypeName;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "usertype")
	public Set<Sysuser> getSysusers() {
		return this.sysusers;
	}*/

	/*public void setSysusers(Set<Sysuser> sysusers) {
		this.sysusers = sysusers;
	}*/
	
}
