package edu.cw.cbr.domain;

// Generated 27.04.2013 1:42:58 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * 
 * Battery generated by hbm2java
 */
@Entity
@Table(name = "battery", schema = "public")
public class Battery{

	private int hardwareComponentId;
	private HardwareComponent hardwareComponent;
	private double capacity;

	public Battery() {
	}

	public Battery(HardwareComponent hardwareComponent, double capacity) {
		this.hardwareComponent = hardwareComponent;
		this.capacity = capacity;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "hardwareComponent"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "hardware_component_id", unique = true, nullable = false)
	public int getHardwareComponentId() {
		return this.hardwareComponentId;
	}

	public void setHardwareComponentId(int hardwareComponentId) {
		this.hardwareComponentId = hardwareComponentId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public HardwareComponent getHardwarecomponent() {
		return this.hardwareComponent;
	}

	public void setHardwarecomponent(HardwareComponent hardwareComponent) {
		this.hardwareComponent = hardwareComponent;
	}

	@Column(name = "capacity", nullable = false, precision = 17, scale = 17)
	public double getCapacity() {
		return this.capacity;
	}

	public void setCapacity(double capacity) {
		this.capacity = capacity;
	}

}
