package edu.cw.cbr.domain;

// Generated 27.04.2013 1:42:58 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Developer generated by hbm2java
 */
@Entity
@Table(name = "developer", schema = "public")
public class Developer{

	private int developerId;
	private String developerName;

	public Developer() {
	}

	public Developer(int developerId, String developerName) {
		this.developerId = developerId;
		this.developerName = developerName;
	}

	@Id
	@Column(name = "developer_id", unique = true, nullable = false)
	public int getDeveloperId() {
		return this.developerId;
	}

	public void setDeveloperId(int developerId) {
		this.developerId = developerId;
	}

	@Column(name = "developer_name", nullable = false, length = 256)
	public String getDeveloperName() {
		return this.developerName;
	}

	public void setDeveloperName(String developerName) {
		this.developerName = developerName;
	}

}
