package edu.cw.cbr.domain;

// Generated 27.04.2013 1:42:58 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * HardwareComponentfamily generated by hbm2java
 */
@Entity
@Table(name = "hardwarecomponentfamily", schema = "public")
public class HardwareComponentfamily{

	private int hardwareComponentFamilyId;
	private Developer developer;
	private HardwareComponentType hardwareComponentType;
	private String hardwareComponentFamilyName;
	private Set<HardwareComponent> hardwareComponents = new HashSet<HardwareComponent>(
			0);

	public HardwareComponentfamily() {
	}

	public HardwareComponentfamily(int hardwareComponentFamilyId,
			Developer developer, HardwareComponentType hardwareComponentType,
			String hardwareComponentFamilyName) {
		this.hardwareComponentFamilyId = hardwareComponentFamilyId;
		this.developer = developer;
		this.hardwareComponentType = hardwareComponentType;
		this.hardwareComponentFamilyName = hardwareComponentFamilyName;
	}

	public HardwareComponentfamily(int hardwareComponentFamilyId,
			Developer developer, HardwareComponentType hardwareComponentType,
			String hardwareComponentFamilyName,
			Set<HardwareComponent> hardwareComponents) {
		this.hardwareComponentFamilyId = hardwareComponentFamilyId;
		this.developer = developer;
		this.hardwareComponentType = hardwareComponentType;
		this.hardwareComponentFamilyName = hardwareComponentFamilyName;
		this.hardwareComponents = hardwareComponents;
	}

	@Id
	@Column(name = "hardware_component_family_id", unique = true, nullable = false)
	public int getHardwareComponentFamilyId() {
		return this.hardwareComponentFamilyId;
	}

	public void setHardwareComponentFamilyId(int hardwareComponentFamilyId) {
		this.hardwareComponentFamilyId = hardwareComponentFamilyId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "developer_id", nullable = false)
	public Developer getDeveloper() {
		return this.developer;
	}

	public void setDeveloper(Developer developer) {
		this.developer = developer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "hardware_component_type_id", nullable = false)
	public HardwareComponentType getHardwarecomponenttype() {
		return this.hardwareComponentType;
	}

	public void setHardwarecomponenttype(
			HardwareComponentType hardwareComponentType) {
		this.hardwareComponentType = hardwareComponentType;
	}

	@Column(name = "hardware_component_family_name", nullable = false, length = 256)
	public String getHardwareComponentFamilyName() {
		return this.hardwareComponentFamilyName;
	}

	public void setHardwareComponentFamilyName(
			String hardwareComponentFamilyName) {
		this.hardwareComponentFamilyName = hardwareComponentFamilyName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hardwarecomponentfamily")
	public Set<HardwareComponent> getHardwarecomponents() {
		return this.hardwareComponents;
	}

	public void setHardwarecomponents(Set<HardwareComponent> hardwareComponents) {
		this.hardwareComponents = hardwareComponents;
	}

}
