package edu.cw.cbr.domain;

// Generated 27.04.2013 1:42:58 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Processor generated by hbm2java
 */
@Entity
@Table(name = "processor", schema = "public")
public class Processor{

	private int hardwareComponentId;
	private HardwareComponent hardwareComponent;
	private int coresNum;
	private float cacheSize;
	private float clockSpeed;

	public Processor() {
	}

	public Processor(HardwareComponent hardwareComponent, int coresNum,
			float cacheSize, float clockSpeed) {
		this.hardwareComponent = hardwareComponent;
		this.coresNum = coresNum;
		this.cacheSize = cacheSize;
		this.clockSpeed = clockSpeed;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "hardwareComponent"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "hardware_component_id", unique = true, nullable = false)
	public int getHardwareComponentId() {
		return this.hardwareComponentId;
	}

	public void setHardwareComponentId(int hardwareComponentId) {
		this.hardwareComponentId = hardwareComponentId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public HardwareComponent getHardwarecomponent() {
		return this.hardwareComponent;
	}

	public void setHardwarecomponent(HardwareComponent hardwareComponent) {
		this.hardwareComponent = hardwareComponent;
	}

	@Column(name = "cores_num", nullable = false)
	public int getCoresNum() {
		return this.coresNum;
	}

	public void setCoresNum(int coresNum) {
		this.coresNum = coresNum;
	}

	@Column(name = "cache_size", nullable = false, precision = 8, scale = 8)
	public float getCacheSize() {
		return this.cacheSize;
	}

	public void setCacheSize(float cacheSize) {
		this.cacheSize = cacheSize;
	}

	@Column(name = "clock_speed", nullable = false, precision = 8, scale = 8)
	public float getClockSpeed() {
		return this.clockSpeed;
	}

	public void setClockSpeed(float clockSpeed) {
		this.clockSpeed = clockSpeed;
	}

}
