package edu.cw.cbr.domain;

// Generated 27.04.2013 1:42:58 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * State generated by hbm2java
 */
@Entity
@Table(name = "state", schema = "public")
public class State{

	private int stateId;
	private float cpuIdlingTime;
	private float amountOfFreeMemory;
	private float batteryCharge;
	private float downloadSpeed;
	private float uploadSpeed;

	public State() {
	}

	public State(int stateId, float cpuIdlingTime, float amountOfFreeMemory,
			float batteryCharge, float downloadSpeed, float uploadSpeed) {
		this.stateId = stateId;
		this.cpuIdlingTime = cpuIdlingTime;
		this.amountOfFreeMemory = amountOfFreeMemory;
		this.batteryCharge = batteryCharge;
		this.downloadSpeed = downloadSpeed;
		this.uploadSpeed = uploadSpeed;
	}

	@Id
	@Column(name = "state_id", unique = true, nullable = false)
	public int getStateId() {
		return this.stateId;
	}

	public void setStateId(int stateId) {
		this.stateId = stateId;
	}

	@Column(name = "cpu_idling_time", nullable = false, precision = 8, scale = 8)
	public float getCpuIdlingTime() {
		return this.cpuIdlingTime;
	}

	public void setCpuIdlingTime(float cpuIdlingTime) {
		this.cpuIdlingTime = cpuIdlingTime;
	}

	@Column(name = "amount_of_free_memory", nullable = false, precision = 8, scale = 8)
	public float getAmountOfFreeMemory() {
		return this.amountOfFreeMemory;
	}

	public void setAmountOfFreeMemory(float amountOfFreeMemory) {
		this.amountOfFreeMemory = amountOfFreeMemory;
	}

	@Column(name = "battery_charge", nullable = false, precision = 8, scale = 8)
	public float getBatteryCharge() {
		return this.batteryCharge;
	}

	public void setBatteryCharge(float batteryCharge) {
		this.batteryCharge = batteryCharge;
	}

	@Column(name = "download_speed", nullable = false, precision = 8, scale = 8)
	public float getDownloadSpeed() {
		return this.downloadSpeed;
	}

	public void setDownloadSpeed(float downloadSpeed) {
		this.downloadSpeed = downloadSpeed;
	}

	@Column(name = "upload_speed", nullable = false, precision = 8, scale = 8)
	public float getUploadSpeed() {
		return this.uploadSpeed;
	}

	public void setUploadSpeed(float uploadSpeed) {
		this.uploadSpeed = uploadSpeed;
	}

}
