package edu.cw.cbr.domain;

// Generated 27.04.2013 1:42:58 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Sysuser generated by hbm2java
 */
@Entity
@Table(name = "sysuser", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "email"))
public class Sysuser{
	private int userId;
	private Usertype usertype;
	private String email;
	private String password;
	private String FName;
	private String LName;
	private boolean isVerified;

	public Sysuser() {
	}

	public Sysuser(int userId, Usertype usertype, String email,
			String password, String FName, String LName,
			boolean isVerified) {
		this.userId = userId;
		this.usertype = usertype;
		this.email = email;
		this.password = password;
		this.FName = FName;
		this.LName = LName;
		this.isVerified = isVerified;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "user_id", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "user_type_id", nullable = false)
	public Usertype getUsertype() {
		return this.usertype;
	}

	public void setUsertype(Usertype usertype) {
		this.usertype = usertype;
	}

	@Column(name = "email", unique = true, nullable = false, length = 256)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password", nullable = false, length = 256)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "f_name", nullable = false, length = 256)
	public String getFName() {
		return this.FName;
	}

	public void setFName(String FName) {
		this.FName = FName;
	}

	@Column(name = "l_name", nullable = false, length = 256)
	public String getLName() {
		return this.LName;
	}

	public void setLName(String LName) {
		this.LName = LName;
	}
	
	@Column(name = "is_verified", nullable = false)
	public boolean isVerified() {
		return isVerified;
	}

	public void setVerified(boolean isVerified) {
		this.isVerified = isVerified;
	}
	

}
